---
abstract: 'Simple, hierarchical user authorization for web applications, with optional support for plan-based (paid) services.'
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Moo: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Abilities
requires:
  Carp: 0
  Hash::Merge: 0
  Moo::Role: 0
  namespace::autoclean: 0
  perl: 5.006
resources:
  homepage: https://github.com/ido50/Abilities
  repository: https://github.com/ido50/Abilities.git
version: 0.5
